local logos = {}

table.insert(logos, {
  "              ........                ",
  "           ..............             ",
  "         ................             ",
  "        ............ ...              ",
  "       ...... ......... .             ",
  "       ....                           ",
  "      . ...    ..    ..               ",
  "      . ... v..hhhhvahh..             ",
  "      . . ..hhhhhhhhhhh..             ",
  "      . .  .ahhhhhhhhhh..             ",
  "      . .    hhhhhhhhhh.              ",
  "        .       hhhhhhh.              ",
  "        .    .hhhhhhhhh. a            ",
  "        .  ..hhhha.hhhh  a            ",
  "        . ahhhhhahhhaa. .h            ",
  "        . ahhhhahhhhhhh ah            ",
  "          .hhhahhhhhhhhah             ",
  "         .ahhhhhhhhhhhh               ",
  "          .hh     hhhhv    ...aav     ",
  "          ahv      hh       ahh.      ",
  "         ahhh              ahhhh.     ",
  "        .h                .hhhhhh     ",
  "                         .hhhhhhhh    ",
  "              .h         ahhhhhhhhv   ",
  "            .ahhh       ahhhhhhhhhh   ",
  "        ..ahhhhhhha.   .hhhhhhhhhhhv  ",
  "        hhhhhhhhhhhh    hhhhhhhhhhhv  ",
})


table.insert(logos, {
  "                                                ",
  "                                                ",
  "                            ,aahhhhav,                         ",
  "                          .vhhhhhhhhhhh,                       ",
  "                        ,aahaahaaaaaaaaah,                     ",
  "                       ahhhhhhhhhhhhhhhhhhh                    ",
  "                      ahhhhhhhahhhhhhhhhhhhh                   ",
  "                      hhhhhhhhhhhhhhhhhhhhhh                   ",
  "                         hhh,         ahhhhh                   ",
  "                         hhh          ahhhhh                   ",
  "                         hhh,        .hhhhhh,                  ",
  "                         hhhhha,, ..vhhahhhhh                  ",
  "                        .hhhhhhhvav,,ahhhhhhhh                 ",
  "                        ahhhh.hah hh.ahh hhhhh,                ",
  "                        ahh hh    h ahh   ahh h                ",
  "                       .hh  .h     .hh    vhhh.                ",
  "                       ahh,, h     ah      hhh.                ",
  "                       .hhhh.h     hh , .aahhh                 ",
  "                        hhhh.,haaaa,aah,.hhh                   ",
  "                          hhhhhhhhhhhhhhh                      ",
  "                          .hhhhhhhhhhhhhh                      ",
  "                         .hhhhhhhhhhhhhhhh                     ",
  "                        .hhhhhhhhhhhhhhhhhh                    ",
  "                        hhhhhhhhhhhhhhhhhhh,                   ",
  "                       .hhhhhhhhhhhhhhhhhhhh                   ",
})

return logos
